# -*- coding: utf-8 -*-
"""P1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9Mg8f4yDfTSPWWio9QG7loiRwIGZc05
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#plt.style.use('ggplot')
import nltk

df = pd.read_csv('Final_Reviews2.csv')
print(df.shape)
df = df.head(500)
print(df.shape)

df.head()

"""#Data cleaning

Find Null Values
"""

df.isnull()

"""Drop Null/Na Values"""

df.dropna()

"""#Quick EDA

"""

ax = df['Score'].value_counts().sort_index() \
    .plot(kind='bar',
          title='Count of Reviews by Stars',
          figsize=(10, 5),
          color = 'black')
ax.set_xlabel('Review Stars')
plt.show()

"""#Basic NLTK"""

example = df['Text'][50]
print(example)

nltk.download('punkt')

tokens = nltk.word_tokenize(example)
tokens[:10]

nltk.download('averaged_perceptron_tagger')

tagged = nltk.pos_tag(tokens)
tagged[:10]

nltk.download('words')

nltk.download('maxent_ne_chunker')

entities = nltk.chunk.ne_chunk(tagged)
entities.pprint()

"""#Step 1. VADER Sentiment Scoring"""

nltk.download('vader_lexicon')

from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

sia = SentimentIntensityAnalyzer()

sia.polarity_scores('I am so happy!')

sia.polarity_scores('This is the worst thing ever.')

sia.polarity_scores(example)

res = {}
for i, row in tqdm(df.iterrows(), total=len(df)):
    text = row['Text']
    myid = row['Id']
    res[myid] = sia.polarity_scores(text)

import itertools
res1 = dict(itertools.islice(res.items(), 10)) 
res1

# convert result to dataframe
vaders = pd.DataFrame(res).T

# merge vaders and df
vaders = vaders.reset_index().rename(columns={'index': 'Id'})
vaders = vaders.merge(df, how='left')

vaders.head(5)

"""#Plot VADER results"""

ax = sns.barplot(data=vaders, x='Score', y='compound')
ax.set_title('Compund Score by Amazon Star Review')
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(12, 3))
sns.barplot(data=vaders, x='Score', y='pos', ax=axs[0])
sns.barplot(data=vaders, x='Score', y='neu', ax=axs[1])
sns.barplot(data=vaders, x='Score', y='neg', ax=axs[2])
axs[0].set_title('Positive')
axs[1].set_title('Neutral')
axs[2].set_title('Negative')
plt.tight_layout()
plt.show()

df1=vaders['Score']
df1.head()

df2=vaders['compound']
corr1=df1.corr(df2)
corr1=round(corr1,3)
print("Corr(X,Y)=",corr1)

plt.scatter(df1, df2)
plt.plot(np.unique(df1), np.poly1d(np.polyfit(df1, df2, 1))
        (np.unique(df1)), color='blue')

sns.relplot(x="pos", y="neg", ci=None, kind="line", hue="neu", data=vaders)
plt.show()

"""#Step 2. Roberta Pretrained Model"""

!pip install transformers

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

print(example)
sia.polarity_scores(example)

encoded_text = tokenizer(example, return_tensors='pt')
output = model(**encoded_text)
scores = output[0][0].detach().numpy()
scores = softmax(scores)
scores_dict = {
    'roberta_neg' : scores[0],
    'roberta_neu' : scores[1],
    'roberta_pos' : scores[2]
}
print(scores_dict)

def polarity_scores_roberta(example):
    encoded_text = tokenizer(example, return_tensors='pt')
    output = model(**encoded_text)
    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    scores_dict = {
        'roberta_neg' : scores[0],
        'roberta_neu' : scores[1],
        'roberta_pos' : scores[2]
    }
    return scores_dict

res = {}
for i, row in tqdm(df.iterrows(), total=len(df)):
    try:
        text = row['Text']
        myid = row['Id']
        vader_result = sia.polarity_scores(text)
        vader_result_rename = {}
        for key, value in vader_result.items():
            vader_result_rename[f"vader_{key}"] = value
        roberta_result = polarity_scores_roberta(text)
        both = {**vader_result_rename, **roberta_result}
        res[myid] = both
    except RuntimeError:
        print(f'Broke for id {myid}')

results_df = pd.DataFrame(res).T
results_df = results_df.reset_index().rename(columns={'index': 'Id'})
results_df = results_df.merge(df, how='left')

results_df

"""#Compare Scores between models"""

results_df.columns

"""#Step 3. Combine and compare"""

results_df2 = results_df.loc[:5 , ["Id", "Score", "vader_neg", "roberta_neg", "vader_pos", "roberta_pos"]].copy()
results_df2

# results_df2.plot(x="Id", y=["vader_pos", "roberta_pos"], kind="bar")
import matplotlib.pyplot as plt
import numpy as np
  
# create data
x = results_df2['vader_neg']
y = results_df2['roberta_neg']
  
# plot lines
plt.plot(x, label = "Vader_neg", linestyle="-.", color = 'blue')
plt.plot(y, label = "Roberta_neg", color = 'orange')
plt.title('Roberta Vs Vader Analysis for Negative Sentiments')
plt.show()

fig, axs = plt.subplots(1, 2, figsize=(12, 3))
axs[0].plot(x, label = "Vader_neu", linestyle="-.")
axs[0].plot(y, label = "Roberta_neu")
axs[1].plot(x, label = "Vader_pos", linestyle="-.")
axs[1].plot(y, label = "Roberta_pos")
axs[0].set_title('Roberta_neu Vs Vader_neu Analysis')
axs[1].set_title('Roberta_pos Vs Vader_pos Analysis')
plt.tight_layout()
plt.show()

sns.pairplot(data=results_df,
             vars=['vader_neg', 'vader_neu', 'vader_pos',
                  'roberta_neg', 'roberta_neu', 'roberta_pos'],
            hue='Score',
            palette='tab10')
plt.show()

"""#Step 4: Review Examples:"""

results_df.query('Score == 1') \
    .sort_values('roberta_pos', ascending=False)['Text'].values[0]

results_df.query('Score == 1') \
    .sort_values('vader_pos', ascending=False)['Text'].values[0]

results_df.query('Score == 5') \
    .sort_values('roberta_neg', ascending=False)['Text'].values[0]

results_df.query('Score == 5') \
    .sort_values('vader_neg', ascending=False)['Text'].values[0]

results_df.query('Score == 3') \
    .sort_values('vader_neg', ascending=False)['Text'].values[0]

"""#Extra: The Transformers Pipeline"""

from transformers import pipeline

sent_pipeline = pipeline("sentiment-analysis")

sent_pipeline('I love sentiment analysis!')

sent_pipeline('Make sure to like and subscribe!')

sent_pipeline('It felt deep in my heart')

sent_pipeline("I am happy")

